theme: jekyll-theme-minimal
title: Hi, I'm Ritadhwaj Roy Choudhury!
description: Junior at the Paul G Allen School of Computer Science and Engineering at University of Washington.
logo: [data/my_photo.jpg]